apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: be-secret
  namespace: prod-be
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bizkit-cluster-secret-store
  target:
    name: be-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/be
