apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: be-allow-required-traffic
  namespace: prod-be
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: be
      app.kubernetes.io/part-of: bizkit
      environment: prod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: system
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-ai-api
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-api
              app.kubernetes.io/part-of: bizkit
              environment: prod
      ports:
        - protocol: TCP
          port: 8000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-data
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - ipBlock:
            cidr: 10.0.4.224/32
      ports:
        - protocol: TCP
          port: 3306
    - to:
        - ipBlock:
            cidr: 10.0.4.37/32
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
