apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/overlays/prod
  - apps/fe/base
  - apps/fe/overlays/prod
  - apps/be/base
  - apps/be/overlays/prod
  - apps/ai-api/base
  - apps/ai-api/overlays/prod
  - apps/ai-model/base
  - apps/ai-model/overlays/prod
  - apps/ai-worker/base
  - apps/ai-worker/overlays/prod
patches:
  - path: patches/fe-replicas.yaml
  - path: patches/be-replicas.yaml
  - path: patches/ai-api-replicas.yaml
  - path: patches/ai-model-replicas.yaml
  - path: patches/ai-worker-replicas.yaml
