apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/be/base
  - ../../apps/be/overlays/prod
  - ../../apps/be/overlays/dev
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: be
        namespace: prod-be
      spec:
        replicas: 1
