apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/ai-api/base
  - ../../apps/ai-api/overlays/prod
  - ../../apps/ai-api/overlays/dev
  - ../../apps/ai-worker/base
  - ../../apps/ai-worker/overlays/prod
  - ../../apps/ai-worker/overlays/dev
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ai-api
        namespace: prod-ai-api
      spec:
        replicas: 1
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ai-worker
        namespace: prod-ai
      spec:
        replicas: 1
