apiVersion: v1
kind: LimitRange
metadata:
  name: dev-default-limits
  namespace: dev
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-fe-default-limits
  namespace: prod-fe
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "300m"
        memory: "512Mi"
      default:
        cpu: "700m"
        memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-be-default-limits
  namespace: prod-be
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "700m"
        memory: "1200Mi"
      default:
        cpu: "1500m"
        memory: "2Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-ai-api-default-limits
  namespace: prod-ai-api
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "500m"
        memory: "800Mi"
      default:
        cpu: "1200m"
        memory: "1536Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-ai-default-limits
  namespace: prod-ai
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "500m"
        memory: "1Gi"
      default:
        cpu: "1500m"
        memory: "3Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-data-default-limits
  namespace: prod-data
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "300m"
        memory: "512Mi"
      default:
        cpu: "1000m"
        memory: "2Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-system-default-limits
  namespace: prod-system
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
