apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fe
  namespace: prod-fe
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fe
      app.kubernetes.io/part-of: bizkit
      environment: prod
