apiVersion: v1
kind: Service
metadata:
  name: fe
  namespace: prod-fe
  labels:
    app.kubernetes.io/name: fe
    app.kubernetes.io/part-of: bizkit
    app.kubernetes.io/component: frontend
    environment: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fe
    app.kubernetes.io/part-of: bizkit
    environment: prod
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
