apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-required-traffic
  namespace: prod-data
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: bizkit
      environment: prod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-be
          podSelector:
            matchLabels:
              app.kubernetes.io/name: be
              app.kubernetes.io/part-of: bizkit
              environment: prod
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-ai-api
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-api
              app.kubernetes.io/part-of: bizkit
              environment: prod
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-ai
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-worker
              app.kubernetes.io/part-of: bizkit
              environment: prod
      ports:
        - protocol: TCP
          port: 6379
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-system
      ports:
        - protocol: TCP
          port: 9121
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
