apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-model-secret
  namespace: prod-ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bizkit-cluster-secret-store
  target:
    name: ai-model-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_ENV
      remoteRef:
        key: prod/ai-model
        property: APP_ENV
    - secretKey: VLLM_BASE_URL
      remoteRef:
        key: prod/ai-model
        property: VLLM_BASE_URL
    - secretKey: VLM_BASE_URL
      remoteRef:
        key: prod/ai-model
        property: VLM_BASE_URL
    - secretKey: RUNPOD_API_KEY
      remoteRef:
        key: prod/ai-model
        property: RUNPOD_API_KEY
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: prod/ai-model
        property: GITHUB_TOKEN
    - secretKey: TAVILY_API_KEY
      remoteRef:
        key: prod/ai-model
        property: TAVILY_API_KEY
    - secretKey: TAVILY_API_KEY_2
      remoteRef:
        key: prod/ai-model
        property: TAVILY_API_KEY_2
    - secretKey: REDIS_URL
      remoteRef:
        key: prod/ai-model
        property: REDIS_URL
    - secretKey: EMBEDDING_SERVICE_URL
      remoteRef:
        key: prod/ai-model
        property: EMBEDDING_SERVICE_URL
    - secretKey: MILVUS_URI
      remoteRef:
        key: prod/ai-model
        property: MILVUS_URI
    - secretKey: MILVUS_TOKEN
      remoteRef:
        key: prod/ai-model
        property: MILVUS_TOKEN
