apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ai-model-allow-required-traffic
  namespace: prod-ai
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ai-model
      app.kubernetes.io/part-of: bizkit
      environment: prod
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-ai-api
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-api
              app.kubernetes.io/part-of: bizkit
              environment: prod
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prod-ai
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ai-worker
              app.kubernetes.io/part-of: bizkit
              environment: prod
      ports:
        - protocol: TCP
          port: 8001
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
