apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fe-secret
  namespace: prod-fe
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bizkit-cluster-secret-store
  target:
    name: fe-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_ENV
      remoteRef:
        key: prod/fe
        property: APP_ENV
    - secretKey: SPRING_API_BASE_URL
      remoteRef:
        key: prod/fe
        property: SPRING_API_BASE_URL
    - secretKey: AI_API_BASE_URL
      remoteRef:
        key: prod/fe
        property: AI_API_BASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: prod/fe
        property: REDIS_URL
    - secretKey: REDIS_NAMESPACE
      remoteRef:
        key: prod/fe
        property: REDIS_NAMESPACE
    - secretKey: SESSION_COOKIE_SECURE
      remoteRef:
        key: prod/fe
        property: SESSION_COOKIE_SECURE
    - secretKey: SESSION_TTL_SECONDS
      remoteRef:
        key: prod/fe
        property: SESSION_TTL_SECONDS
    - secretKey: MAX_SESSION_LIFETIME
      remoteRef:
        key: prod/fe
        property: MAX_SESSION_LIFETIME
    - secretKey: MIN_ROTATION_INTERVAL
      remoteRef:
        key: prod/fe
        property: MIN_ROTATION_INTERVAL
    - secretKey: SENTRY_AUTH_TOKEN
      remoteRef:
        key: prod/fe
        property: SENTRY_AUTH_TOKEN
    - secretKey: SENTRY_DSN
      remoteRef:
        key: prod/fe
        property: SENTRY_DSN
    - secretKey: SENTRY_ENVIRONMENT
      remoteRef:
        key: prod/fe
        property: SENTRY_ENVIRONMENT
