apiVersion: v1
kind: Service
metadata:
  name: ai-model
  labels:
    app.kubernetes.io/name: ai-model
    app.kubernetes.io/part-of: bizkit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-model
  ports:
    - name: http
      port: 8000
      targetPort: http
