apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: be-env
  labels:
    app.kubernetes.io/name: be
    app.kubernetes.io/part-of: bizkit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: be-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: TODO_BE_SECRET_KEY # TODO(B): 환경별 외부 시크릿 경로로 교체
