apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: be
  namespace: prod-be
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be
      app.kubernetes.io/part-of: bizkit
      environment: prod
