apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bizkit-cluster-secret-store
spec:
  provider:
    vault:
      server: https://10.0.255.98:8200
      path: secret
      version: v2
      caProvider:
        type: ConfigMap
        namespace: system
        name: vault-ca
        key: ca.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: bizkit-prod-cluster-external-secrets-role
          serviceAccountRef:
            name: external-secrets
            namespace: system
