installCRDs: true

serviceAccount:
  create: true
  name: external-secrets

replicaCount: 1
nodeSelector:
  node-pool: system
tolerations:
  - key: dedicated
    operator: Equal
    value: system
    effect: NoSchedule

leaderElect: true
priorityClassName: bizkit-system-critical

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 200m
    memory: 192Mi

webhook:
  create: true
  replicaCount: 1
  priorityClassName: bizkit-system-critical
  nodeSelector:
    node-pool: system
  tolerations:
    - key: dedicated
      operator: Equal
      value: system
      effect: NoSchedule
  certManager:
    enabled: false
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 96Mi

certController:
  create: true
  replicaCount: 1
  priorityClassName: bizkit-system-critical
  nodeSelector:
    node-pool: system
  tolerations:
    - key: dedicated
      operator: Equal
      value: system
      effect: NoSchedule
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 96Mi
