apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca
  namespace: prod-system
  labels:
    app.kubernetes.io/name: vault-ca
    app.kubernetes.io/part-of: bizkit
    app.kubernetes.io/component: system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFDDCCAvSgAwIBAgIUakTk37jhdJsdxDz4bVgWTQuRf8MwDQYJKoZIhvcNAQEL
    BQAwEDEOMAwGA1UEAwwFdmF1bHQwHhcNMjYwMzE3MDg0MjQwWhcNMjgwNjE5MDg0
    MjQwWjAQMQ4wDAYDVQQDDAV2YXVsdDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBAJAJTJuhakNf+Vz5OJ9uBp1mfqhMyCO0SfDzPCKvxmL5LVD8OPqipgrY
    JIwtxEoGnfuZoEWB/ufIH8tXc/e76UBNiKMuHcKueTaQC/M5jY8d4yflo6HgOwfi
    Z69n2hqk7zEut5dx84lj6qJnLj4tk1oDyFpPdp0VBP2JOEmhXtXKFjCMWFW41fu3
    Fo52ZZ4Q+h5MPRFV4UsFC3NGbRyexkvpabuoBvYZv7dm1zIYkbUbiP1V/l+Zt3PY
    16/yPQ5cYFfIVE7fbXq+phhlha1G/rZb7TkLN3Ksy2BDngULf3JQcEEei6YEChi7
    J8bpVMBLaOj77tQGg7AIdahlqXeKXd8rppRqTU1O/9k8q6Hi7q+1/x833rhxJM6h
    PB8F27gWKH9ebpHzUNXajKNpqwQkXx9/AK6ldOni8AK60rIQv9TQePmKTMPdL9q3
    Qbx/4IbYIsujbCKB7l6vTOW3+MFO4pzeDK3/ipwDLp6WpwuPfOHTOx/t9uQ4CpSx
    IjqlhO2GkkwZaAk92ueRhQ3Jo8dSEnfvX6cpifRUakce3uqtIQ0wx6yMfZenXPbz
    hj76qR50JnKqFFDyOulub3awv5jLrtc5UzAqvYG5CgY85FIV/iz3P03JC1AoHWHI
    zSoqksrT+4a2bRqv4aIRnI30Eylav2B27XChrAc1nkHQ9X3o7qfXAgMBAAGjXjBc
    MCYGA1UdEQQfMB2CBXZhdWx0gg5pcC0xMC0wLTI1NS05OIcECgD/YjATBgNVHSUE
    DDAKBggrBgEFBQcDATAdBgNVHQ4EFgQU8CHNqxAFPFcSUSHWQjzWPKgTn0YwDQYJ
    KoZIhvcNAQELBQADggIBADsQ//YhXyfRj3UO92wJnXZfjFDV2tGUkoV9UX4AJowO
    VZMMaEBb51xx7LG+VtDZUJjmQm1feQmzek3O9L1s2RxgLxmJMHQrSPsGlESZkTtN
    RZOQXgzOhHaaRqR2hvlvBfBXk1YqTe8aIkFJPyR+YPoRB0puzdOiy/zthV1URA1s
    7FW14Hk6h1thn8EMbivazp2E4gAy0hDlgeDmo58KmkmjyQx7i+xs2oZg1Gt+qVWk
    DNmzSIV5a7282LuSe/rIM53LX1E22eucZd68oSfqaX5Z9jqgEv/PKLhQiKQuHXA7
    1TGoXk5woPjpZCc+6szDm+ng3kXY7IcR2VaAaZEZvoK41go+hqpKwSaKk4NqGOLk
    9JnESM8R6/WFXA52D0hkQ8jjbTLlDhvkcKUqZHtfSXdwMkf1X38BXS8sHPDemRkB
    queeztzdpiGw3rHnsAE87PphTjmiEUEHEsxElOU/KDbDQK+PMZDpM3AAe+xn7ST0
    hF/pl6XJ6RFlkNZYov5YKqgwrUbPxpW5SInXdW7QmMhJHDKYcMGvzuZ6g0DHVefG
    VAncveE8A0/YUGlBw3zfdI2ixfSPteSEfzXXMpYO0dGBKaWjW23uWrmruE9xLMXe
    FGnppIeftKcxYDGOR0FnUYHo3MhYDASH4jkcMngKWDKyyCOKlvCE5XHrfXZj1Fxc
    -----END CERTIFICATE-----
