apiVersion: v1
kind: Service
metadata:
  name: ai-worker
  namespace: prod-ai
  labels:
    app.kubernetes.io/name: ai-worker
    app.kubernetes.io/part-of: bizkit
    app.kubernetes.io/component: ai-worker
    environment: prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ai-worker
    app.kubernetes.io/part-of: bizkit
    environment: prod
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
