apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-fe
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-be
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-ai-api
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-ai
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-data
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-system
  labels:
    app.kubernetes.io/part-of: bizkit
    environment: prod
