apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-api
  namespace: prod-ai-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-api
      app.kubernetes.io/part-of: bizkit
      environment: prod
